- name: install postgres-9.3 repo on Redhat / CentOS 7.
  yum: name={{ dataverse.postgres_repo }} state=present
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: postgres

- name: install postgres-9.3 on RedHat / CentOS 7.
  yum: name=postgresql93-server state=latest
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: postgres

- name: init postgres-9.3 on RedHat / CentOS 7.
  shell: /usr/pgsql-9.3/bin/postgresql93-setup initdb
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: postgres

- name: install and init postgres-9.3 for Debian/Ubuntu
  apt: pkg=postgresql-9.3 state=latest update_cache=true
  when: ansible_os_family == "Debian"
  tags: postgres

- name: install pg_hba.conf on RedHat / CentOS 7.
  copy: src=pg_hba.conf dest=/var/lib/pgsql/9.3/data
        owner=postgres group=postgres mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: postgres

- name: enable postgres-9.3 on RedHat / CentOS 7.
  service: name=postgresql-9.3 enabled=yes
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: postgres

- name: start postgres-9.3 on RedHat / CentOS 7.
  service: name=postgresql-9.3 state=started
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: postgres

- name: install pg_hba.conf on Debian/Ubuntu
  copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main
        owner=postgres group=postgres mode=0644
  when: ansible_os_family == "Debian"
  tags: postgres

- name: restart postgres on Debian/Ubuntu
  service: name=postgresql state=restarted
  when: ansible_os_family == "Debian"
  tags: postgres

- name: create glassfish postgres database
  postgresql_db: name={{ dataverse.db }}
  tags: postgres

- name: create glassfish postgres user, set permissions
  postgresql_user: db={{ dataverse.db }} name={{ dataverse.dbuser }}
        password={{ dataverse.dbpass }}
        role_attr_flags=NOSUPERUSER,CREATEDB,CREATEROLE,INHERIT,LOGIN
  tags: postgres
