---

- name: ensure EPEL repository for RedHat7/CentOS7
  yum: name=epel-release state=latest
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: prereqs

- name: install java-1.8.0-openjdk-devel for RedHat/CentOS. Dataverse currently requires this version.
  yum: name="{{item}}" state=latest
  with_items:
    - elinks
    - git
    - java-1.8.0-openjdk-devel
    - jq
    - net-tools
    - perl
    - python-psycopg2
    - unzip
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: prereqs

- name: install ImageMagick for RedHat/CentOS to allow thumbnail generation
  yum: name=ImageMagick state=latest
  when: 
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"
    - "{{ dataverse.thumbnails }}"
  tags: prereqs

- name: install openjdk-8-jdk, apache, etc. for Ubuntu/Debian.
  apt: name="{{item}}" state=latest update_cache=true
  with_items:
    - apache2
    - git
    - jq
    - libapache2-mod-shib2
    - openjdk-8-jdk
    - perl5
    - python-psycopg2
    - unzip
  when: ansible_os_family == "Debian"
  tags: prereqs

- name: install ImageMagick for Debian/Ubuntu to allow thumbnail generation
  apt: name=ImageMagick state=latest
  when: ansible_os_family == "Debian"
        "{{ dataverse.thumbnails }}" == true
  tags: prereqs
