---

# version numbers changed on github. only used this because files were missing from install.zip
#- name: clone {{ dataverse.version }} from git. optimally replace install.zip with this.
#  git: repo=git://github.com/IQSS/dataverse.git dest=/tmp/dataverse_{{ dataverse.version }} version={{ dataverse.version }}
#       clone=yes depth=1 accept_hostkey=true
#  tags: dataverse

- name: download dataverse installer. unarchive urls supported in ansible 2.0
  get_url: url=https://github.com/IQSS/dataverse/releases/download/v{{ dataverse.version }}/dvinstall.zip dest=/tmp mode=0644
  tags: dataverse

- name: unzip dataverse installer
  shell: unzip /tmp/dvinstall.zip -d /tmp
  tags: dataverse

- name: install jdbc driver
  shell: "/bin/cp /tmp/dvinstall/pgdriver/postgresql-9.1-902.jdbc4.jar {{ dataverse.glassfish.root }}/glassfish/lib/"
  tags: dataverse

- name: copy jhove config
  copy: src=jhove.conf dest={{ dataverse.glassfish.root }}/domains/glassfish/{{ dataverse.glassfish.domain }}/config/ owner=root group=root mode=0644
  tags: dataverse

- name: run glassfish-setup.sh
  shell: "cd /tmp/dvinstall && nohup ./glassfish-setup.sh > /tmp/glassfish-setup.out 2>&1"
  become: yes
  become_user: "{{ dataverse.glassfish.user }}"
  environment:
    HOST_ADDRESS: "{{ dataverse.service_name }}"
    GLASSFISH_ROOT: "{{ dataverse.glassfish.root }}"
    GLASSFISH_DOMAIN: "{{ dataverse.glassfish.domain }}"
    FILES_DIR: "{{ dataverse.filesdir }}"
    DB_NAME: "{{ dataverse.db }}"
    DB_PORT: "{{ dataverse.dbport }}"
    DB_HOST: "{{ dataverse.dbhost }}"
    DB_USER: "{{ dataverse.dbuser }}"
    DB_PASS: "{{ dataverse.dbpass }}"
    RSERVE_HOST: "{{ rserve.host }}"
    RSERVE_PORT: "{{ rserve.port }}"
    RSERVE_USER: "{{ rserve.user }}"
    RSERVE_PASS: "{{ rserve.pass }}"
    SMTP_SERVER: "{{ dataverse.smtp }}"
    MEM_HEAP_SIZE: "{{ dataverse.memheap }}"

- name: set logging format
  become: yes
  become_user: "{{ dataverse.glassfish.user }}"
  shell: "{{ dataverse.glassfish.root }}/bin/asadmin set-log-file-format {{ dataverse.glassfish.logformat }}"

- name: deploy dataverse.war
  become: yes
  become_user: "{{ dataverse.glassfish.user }}"
  shell: "nohup {{ dataverse.glassfish.root }}/bin/asadmin deploy /tmp/dvinstall/dataverse.war"
