---
- name: copy ssl cert
  copy:
    src: '{{ apache.ssl.cert }}'
    dest: '/etc/pki/tls/certs/{{ apache.ssl.cert }}'
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: copy ssl chain
  copy:
    src: '{{ apache.ssl.interm }}'
    dest: '/etc/pki/tls/certs/{{ apache.ssl.interm }}'
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: copy ssl key
  copy:
    src: '{{ apache.ssl.key }}'
    dest: '/etc/pki/tls/private/{{ apache.ssl.key }}'
    owner: root
    group: root
    mode: 0400
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: install http redirect template
  template: src=http.redirect.conf.j2 dest=/etc/httpd/conf.d/http.redirect.conf
        owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: install ssl proxy template
  template: src=ssl.conf.j2 dest=/etc/httpd/conf.d/ssl.conf
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

