- name: ansible tasks like variables, not group_vars
  set_fact:
    siteUrl: '{{ dataverse.glassfish.siteurl }}'

- name: if siteUrl not passed, use fqdn. fix protocol and port in proxy branch.
  set_fact:
    siteUrl: 'http\://{{ ansible_fqdn }}\:8080'
  when: siteUrl |length < 1

- name: are we in EC2?
  uri:
    url: http://169.254.169.254/latest/meta-data/
    timeout: 2
  register: aws_uri_check
  failed_when: False

- set_fact:
    is_aws_environment: "{{ aws_uri_check.status == 200 }}"

- name: if we're in EC2, get public hostname
  shell: 'curl http://169.254.169.254/latest/meta-data/public-hostname'
  register: ec2_output
  when: is_aws_environment

- name: if we're in EC2, set public hostname
  set_fact:
    public_hostname: "{{ ec2_output.stdout }}"
  when: is_aws_environment

- name: now correct siteUrl
  set_fact:
    siteUrl: 'http\://{{ public_hostname}}\:8080'
  when: is_aws_environment

- name: debug siteurl
  debug:
    msg: "siteurl is {{ siteUrl }}"

- name: set siteurl
  become: yes
  become_user: "{{ dataverse.glassfish.user }}"
  shell: '{{ glassfish_dir}}/bin/asadmin create-jvm-options "-Ddataverse.siteUrl={{ siteUrl }}"'
