---
# dataverse/tasks/dataverse-prereqs.yml

- name: yum clean all, sigh...
  shell: 'yum clean all'
  when: ansible_os_family == "RedHat"

- name: let's use the closest centos mirror
  file:
    path: /var/cache/yum/x86_64/7/timedhosts.txt
    state: absent
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: makecache
  yum:
    update_cache: yes
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: ensure EPEL repository for RHEL/CentOS
  yum: name=epel-release state=latest
  when: ansible_os_family == "RedHat"

- name: CentOS8 needs PowerTools
  shell: "dnf config-manager --enable PowerTools"
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "8"

- name: install java-nnn-openjdk and other packages for RedHat/CentOS.
  yum:
   name: ['bash-completion', 'elinks', 'git', 'java-{{ dataverse.java.version }}-openjdk-devel', 'jq', 'mlocate', 'net-tools', 'perl', 'sudo', 'unzip', 'vim-enhanced']
   state: latest
  when: ansible_os_family == "RedHat"
  tags: prereqs

- name: install ImageMagick for RHEL/CentOS7 to allow thumbnail generation
  yum: name=ImageMagick state=latest
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"
    - dataverse.thumbnails
  tags: prereqs

- name: install GraphicsMagic on RHEL/CentOS8
  dnf:
    name: GraphicsMagick
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"
    - dataverse.thumbnails
  tags: prereqs
