---
# dataverse/tasks/dataverse-install.yml

# version numbers changed on github. only used this because files were missing from install.zip
#- name: clone {{ dataverse.version }} from git. optimally replace install.zip with this.
#  git: repo=git://github.com/IQSS/dataverse.git dest=/tmp/dataverse_{{ dataverse.version }} version={{ dataverse.version }}
#       clone=yes depth=1 accept_hostkey=true

- name: download dataverse installer
  get_url:
    url: https://github.com/IQSS/dataverse/releases/download/v{{ dataverse.version }}/dvinstall.zip
    dest: /tmp
    # checksum: sha1:7ef1fb48956cfd509e55488f2908e9a4ae923a45 # requires ansible ≥2.0

- name: unzip dataverse installer
  unarchive:
    src: /tmp/dvinstall.zip
    remote_src: true
    dest: /tmp

- include: dataverse-build.yml
  when: dataverse_branch != "release"
  
- name: fix perms on dataverse-war
  file: path=/tmp/dvinstall/dataverse.war mode=0644

- name: set jdbcurl
  set_fact: jdbcurl='{{ dataverse.postgres.jdbcurl }}'

- name: install release jdbc driver
  shell: "/bin/cp /tmp/dvinstall/pgdriver/postgresql-*.jar {{ glassfish_dir }}/glassfish/lib/"
  when: jdbcurl|length == 0

- name: install custom jdbc driver
  get_url:
    url: '{{ dataverse.postgres.jdbcurl }}'
    dest: '{{ glassfish_dir }}/glassfish/lib/'
  when: jdbcurl | length > 0

- name: copy jhove configs
  shell: "cp /tmp/dvinstall/jhove* {{ glassfish_dir }}/glassfish/domains/{{ dataverse.glassfish.domain }}/config"

- name: bash aliases won't expand in non-interactive shells
  lineinfile:
    path: /tmp/dvinstall/glassfish-setup.sh
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: 'rserve_password_alias', line: '  ./asadmin $ASADMIN_OPTS create-jvm-options "\-Ddataverse.rserve.password=${RSERVE_PASS}"' }
    - { regexp: 'doi_password_alias', line: '  ./asadmin $ASADMIN_OPTS create-jvm-options "\-Ddoi.password=${DOI_PASSWORD}"' }
    - { regexp: 'db_password_alias', line: '  ./asadmin $ASADMIN_OPTS set resources.jdbc-connection-pool.dvnDbPool.property.password="${DB_PASS}"' }

- name: run glassfish-setup.sh
  shell: "nohup ./glassfish-setup.sh > /tmp/glassfish-setup.out 2>&1"
  become: yes
  become_user: "{{ dataverse.glassfish.user }}"
  environment:
    HOST_ADDRESS: "{{ servername }}"
    GLASSFISH_ROOT: "{{ glassfish_dir }}"
    GLASSFISH_DOMAIN: "{{ dataverse.glassfish.domain }}"
    FILES_DIR: "{{ dataverse.filesdir }}"
    DB_NAME: "{{ dataverse.db.name }}"
    DB_PORT: "{{ dataverse.db.port }}"
    DB_HOST: "{{ dataverse.db.host }}"
    DB_USER: "{{ dataverse.db.user }}"
    DB_PASS: "{{ dataverse.db.pass }}"
    RSERVE_HOST: "{{ rserve.host }}"
    RSERVE_PORT: "{{ rserve.port }}"
    RSERVE_USER: "{{ rserve.user }}"
    RSERVE_PASS: "{{ rserve.pass }}"
    SMTP_SERVER: "{{ dataverse.smtp }}"
    MEM_HEAP_SIZE: "{{ dataverse.memheap }}"
    DOI_BASEURL: "{{ dataverse.doi.baseurl }}"
    DOI_USERNAME: "{{ dataverse.doi.username }}"
    DOI_PASSWORD: "{{ dataverse.doi.password }}"
  args:
    chdir: /tmp/dvinstall
    executable: /bin/bash

- name: negate need for password aliases
  file:
    name: /tmp/glassfish-setup.out
    mode: 0600

- name: set logging format
  become: yes
  become_user: "{{ dataverse.glassfish.user }}"
  shell: "{{ glassfish_dir }}/bin/asadmin set-log-file-format {{ dataverse.glassfish.logformat }}"

- include: jacoco-instrument.yml
  when: dataverse.jacoco.enabled == true

- name: deploy dataverse.war
  become: yes
  become_user: "{{ dataverse.glassfish.user }}"
  shell: "nohup {{ glassfish_dir }}/bin/asadmin deploy /tmp/dvinstall/dataverse.war"
