# datavarse/tasks/dataverse-build.yml

- name: install maven
  yum:
    name: maven
    state: latest

# ----- wedge in dataverse-bundled files before building from branch ---------
- name: copy api scripts from branch into /tmp/dvinstall
  copy:
    src: "{{ item }}"
    dest: "/tmp/dvinstall/"
    remote_src: yes
  with_items:
    - "{{ dataverse.srcdir }}/scripts/api/setup-datasetfields.sh"
    - "{{ dataverse.srcdir }}/scripts/api/setup-users.sh"
    - "{{ dataverse.srcdir }}/scripts/api/setup-builtin-roles.sh"
    - "{{ dataverse.srcdir }}/scripts/api/setup-dvs.sh"
    - "{{ dataverse.srcdir }}/scripts/api/setup-identity-providers.sh"
    - "{{ dataverse.srcdir }}/scripts/api/setup-all.sh"
    - "{{ dataverse.srcdir }}/scripts/api/post-install-api-block.sh"

# remote copy doesn't currently support recursive copy of directory
#- name: copy api script data directory
#  copy:
#    src: "{{ dataverse.srcdir }}/scripts/api/data"
#    dest: "/tmp/dvinstall/"
#    remote_src: yes

- name: copy api script data directory
  shell: "/bin/cp -r {{ dataverse.srcdir }}/scripts/api/data /tmp/dvinstall/"

- name: copy remaining files from branch
  copy:
    src: "{{ item }}"
    dest: "/tmp/dvinstall/"
    remote_src: yes
  with_items:
    - "{{ dataverse.srcdir }}/scripts/database/reference_data.sql"
    - "{{ dataverse.srcdir }}/conf/jhove/jhove.conf"
    - "{{ dataverse.srcdir }}/conf/jhove/jhoveConfig.xsd"

# TODO: fix commit variable registration
#- name: get branch_commit
#  command: 'cd "{{ dataverse.srcdir }}" && git log --oneline | head -1 | awk "{print $1}")'
#  register: bcout
#
#- debug:
#    msg: "bcout is {{ bcout }}"
#
#- set_fact:
#    commit='{{ bcout.stdout.split(" ")[0] }}'
#
#- debug:
#    msg: "commit is {{ commit }}"

- name: add branch name, branch_commit to BuildNumber.properties
  lineinfile:
    path: "{{ dataverse.srcdir }}/src/main/java/BuildNumber.properties"
    line: "build.number={{ dataverse_branch }}"
    create: yes

- name: build warfile. tail /tmp/dataverse/mvn.out for gory details.
  shell: "mvn -Dmaven.test.skip=true package > mvn.out"
  args:
    chdir: "{{ dataverse.srcdir }}"

- name: copy warfile over release
  copy:
    src: "{{ dataverse.srcdir }}/target/dataverse-{{ dataverse.version }}.war"
    dest: "/tmp/dvinstall/dataverse.war"
    backup: yes
    remote_src: yes
