---
# dataverse/tasks/dataverse-install.yml

# version numbers changed on github. only used this because files were missing from install.zip
#- name: clone {{ dataverse.version }} from git. optimally replace install.zip with this.
#  git: repo=git://github.com/IQSS/dataverse.git dest=/tmp/dataverse_{{ dataverse.version }} version={{ dataverse.version }}
#       clone=yes depth=1 accept_hostkey=true

- name: run dataverse installer
  debug:
    msg: '##### DATAVERSE INSTALLER #####'

- name: download dataverse installer
  get_url:
    url: https://github.com/IQSS/dataverse/releases/download/v{{ dataverse.version }}/dvinstall.zip
    dest: /tmp

- name: unzip dataverse installer
  unarchive:
    src: /tmp/dvinstall.zip
    remote_src: true
    dest: /tmp

- include: dataverse-build.yml
  when: dataverse_branch != "release"
  
- name: fix perms on dataverse-war
  file: path=/tmp/dvinstall/dataverse.war mode=0644

- name: set jdbcurl
  set_fact: jdbcurl='{{ db.postgres.jdbcurl }}'

- name: install release jdbc driver
  shell: "/bin/cp /tmp/dvinstall/pgdriver/postgresql-*.jar {{ glassfish_dir }}/glassfish/lib/"
  when: jdbcurl|length == 0

- name: install custom jdbc driver
  get_url:
    url: '{{ db.postgres.jdbcurl }}'
    dest: '{{ glassfish_dir }}/glassfish/lib/'
  when: jdbcurl | length > 0

# python3 installer calls as-setup.sh
- name: bash aliases won't expand in non-interactive shells
  lineinfile:
    path: /tmp/dvinstall/as-setup.sh
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: 'rserve_password_alias', line: '  ./asadmin $ASADMIN_OPTS create-jvm-options "\-Ddataverse.rserve.password=${RSERVE_PASS}"' }
    - { regexp: 'doi_password_alias', line: '  ./asadmin $ASADMIN_OPTS create-jvm-options "\-Ddoi.password=${DOI_PASSWORD}"' }
    - { regexp: 'db_password_alias', line: '  ./asadmin $ASADMIN_OPTS set "resources.jdbc-connection-pool.dvnDbPool.property.password=${DB_PASS}"' }

- name: ensure as-setup.sh is executable
  file:
    path: /tmp/dvinstall/as-setup.sh
    mode: 0755

- name: grab current copies of installer source
  get_url:
    url: 'https://raw.githubusercontent.com/IQSS/dataverse/develop/scripts/installer/{{ item }}'
    dest: '/tmp/dvinstall/{{ item }}'
    mode: '0755'
  with_items:
    - install.py
    - installConfig.py
    - installAppServer.py
    - installUtils.py

- name: place default.config
  template:
    src: default.config.j2
    dest: /tmp/dvinstall/default.config
    owner: root
    group: root
    mode: 0644

- name: fire off installer
  become: true
  become_user: '{{ dataverse.glassfish.user }}'
  shell: /usr/bin/python3 /tmp/dvinstall/install.py -f --config_file=default.config --noninteractive
  args:
    chdir: /tmp/dvinstall

# install.py doesn't currently log this output
#- name: negate need for password aliases
#  file:
#    name: /tmp/as-setup.out
#    mode: 0600
#  ignore_errors: yes

- name: set logging format
  become: yes
  become_user: "{{ dataverse.glassfish.user }}"
  shell: "{{ glassfish_dir }}/bin/asadmin set-log-file-format {{ dataverse.glassfish.logformat }}"

- include: jacoco-instrument.yml
  when: dataverse.jacoco.enabled == true and
        dataverse_repo != "release"
