# dataverse/tasks/dataverse-build.yml

- name: install maven
  yum:
    name: maven
    state: latest

- name: update system libraries on this ancient centos-7.1 image
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - curl
  - libcurl
  - nss

- name: clone specified branch
  git:
    repo: "{{ dataverse.git.repo }}"
    dest: /tmp/dataverse
    version: "{{ dataverse.git.branch }}"

# use shell until we upgrade ansible. sigh.
#- name: clone specified branch
#  shell: "cd /tmp && git clone -b {{ dataverse.git.branch }} {{ dataverse.git.repo }}"

- name: build warfile. tail /tmp/dataverse/mvn.out for gory details.
  shell: "mvn -Dmaven.test.skip=true package > mvn.out"
  args:
    chdir: /tmp/dataverse

#- name: copy warfile over release
#  copy:
#    remote_src: "/tmp/dataverse/target/dataverse-{{ dataverse.version }}.war"
#    dest: "/tmp/dvinstall/dataverse-{{ dataverse.version }}.war"
#    backup: yes

# use shell until we upgrade ansible.
- name: copy warfile over release
  shell: "cp /tmp/dataverse/target/dataverse-{{ dataverse.version }}.war /tmp/dvinstall/dataverse.war"
