# dataverse/tasks/dataverse-branch.yml

- name: clone specified branch
  git:
    repo: "{{ dataverse_repo }}"
    dest: "{{ dataverse.srcdir }}"
    version: "{{ dataverse_branch }}"
  when: dataverse_branch != "release"
