---

- name: download jacoco
  debug:
    msg: '##### DOWNLOAD JACOCO #####'

- name: ensure jacoco home exists
  file:
    path: '{{ dataverse.jacoco.home }}'
    state: directory
    mode: '0755'

- name: download jacoco. currently 0.8.1 is required per pom.xml
  unarchive:
    src: https://repo1.maven.org/maven2/org/jacoco/jacoco/{{ dataverse.jacoco.version }}/jacoco-{{ dataverse.jacoco.version }}.zip
    dest: '{{ dataverse.jacoco.home }}'
    remote_src: yes
