---

- name: ensure dot dir exists
  file:
    path: '~/.aws'
    state: directory
    mode: '0700'
    
- name: place aws credentials
  template:
    src: aws_credentials.j2
    dest: '~/.aws/credentials'
    mode: '0600'

- name: place aws config
  template:
    src: aws_config.j2
    dest: '~/.aws/config'
    mode: '0600'

- name: escape custom endpoint url colons
  set_fact: "custom_endpoint_escaped={{ s3.custom_endpoint_url | regex_replace (':','\\:') }}"
  when: s3.custom_endpoint_url | length > 0

- name: create localstack bucket for testing
  shell: 'aws --endpoint={{ custom_endpoint_escaped }} s3 mb s3://{{ s3.bucket_name }}'
  when: s3.custom_endpoint_url | length > 0
