---
# dataverse/tasks/main.yml

- include: dataverse-prereqs.yml
  tags: prereqs

- include: dataverse-apache.yml
  tags: apache

- include: dataverse-shibboleth.yml
  when: shibboleth.enabled == True
  tags: shibboleth

- include: dataverse-postgres.yml
  tags: postgres

- include: dataverse-branch.yml
  when: dataverse_branch != "release"

- include: dataverse-glassfish.yml
  tags: glassfish

- include: dataverse-solr.yml
  tags: solr

- include: dataverse-install.yml
  tags: dataverse

- include: dataverse-postinstall.yml
  tags: postinstall

- include: dataverse-sampledata.yml
  when: dataverse.sampledata.enabled == true
  tags: sampledata

- include: dataverse-counter.yml
  when: dataverse.counter.enabled == true
  tags: counter

- include: dataverse-previewers.yml
  when: dataverse.previewers.enabled == true
  tags: previewers

- include: dataverse-wholetale.yml
  when: dataverse.wholetale.enabled == true
  tags: wholetale
