---

- name: systemd no likey escaped colons
  set_fact:
    siteUrl: "{{ siteUrl | regex_replace('\\\\:', ':') }}"
  tags: grafana

- debug:
    msg: "siteUrl is {{ siteUrl }}"

- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

- include: collectd.yml

- name: add prometheus service account
  user:
    name: '{{ prometheus.user }}'

- name: unarchive won't create directory
  file:
    path: '{{ prometheus.root }}'
    state: directory
    owner: '{{ prometheus.user }}'
    mode: '0755'

- name: install prometheus
  unarchive:
    src: '{{ prometheus.url }}'
    dest: '{{ prometheus.root }}'
    owner: '{{ prometheus.user }}'
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: copy prometheus config file
  copy:
    src: prometheus.yml
    dest: '{{ prometheus.root }}/prometheus.yml'
    owner: '{{ prometheus.user }}'
    mode: 0644

- name: node_exporter dir must exist
  file:
    path: '{{ prometheus.root }}/node_exporter'
    state: directory
    owner: '{{ prometheus.user }}'
    mode: '0755'

- name: install node_exporter
  unarchive:
    src: '{{ prometheus.node_exporter }}'
    dest: '{{ prometheus.root }}/node_exporter'
    remote_src: yes
    extra_opts: [--strip-components=1]
    
- name: place prometheus systemd template
  template:
    src: prometheus.service.j2
    dest: /usr/lib/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644

- name: place node_exporter systemd template
  template:
    src: node_exporter.service.j2
    dest: /usr/lib/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644

- name: ensure /etc/jmx_exporter exists
  file:
    path: /etc/jmx_exporter
    state: directory

- name: place jmx_export config.yaml
  copy:
    src: jmx_exporter_config.yml
    dest: /etc/jmx_exporter/config.yml
    owner: root
    group: root
    mode: 0644

- name: payara should load jmx_exporter agent
  lineinfile:
    path: /usr/lib/systemd/system/glassfish.service
    regexp: '^ExecStart(.*)'
    line: 'ExecStart = /usr/bin/java -javaagent:{{ glassfish_dir }}/glassfish/lib/jmx_prometheus_javaagent.jar=8888:/etc/jmx_exporter/config.yml -jar {{ glassfish_dir }}/glassfish/lib/client/appserver-cli.jar start-domain'

- name: reload systemd
  shell: systemctl daemon-reload

- name: start and enable prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes

- name: give prometheus a breather
  pause:
    seconds: 2

- name: start and enable node_exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes

- include: grafana.yml

- name: restart glassfish to enable jmx_exporter agent
  systemd:
    name: glassfish
    state: restarted
